### ISSUE TITLE
Carla on Colab

### ISSUE THREAD

**Issue by Mouni97AS** [Shuntw6096/swda-detectron2#8]

**Comment by Mouni97AS** [comment]
Hi,
I was trying to reach you.
I need your help to run carla on Colab based on the repos[remocloab](https://github.com/demotomohiro/remocolab)
how you set the path for cloudflared?

**Comment by Shuntw6096** [comment]
Hi, I haven't use [remocolab](https://github.com/demotomohiro/remocolab) for a long time, I'm sorry I had not helped, but you maybe can ask [remocolab](https://github.com/demotomohiro/remocolab) for help, I remember that I not set the path, just call cloudflared directly on my win10.
``` bash
# .\cloudflared.exe ...
.\cloudflared.exe --help 
```
